config/routes.rb
RssFeedReader::Application.routes.draw do
  
  resources :subscriptions, only: [:index]


  devise_for :users#, controllers: {:registrations => "registrations", sessions: "sessions"}

  devise_scope :user do
    resources :users, only: [:index]
  end 

  root to: 'home#index'

  resources :articles

  resources :comments

  resources :bookmarks

  resources :categories

  resources :friendships

  get '/users/:user_id/profile', to: "profiles#show", as: :user_profile

  get :profile,        to: "profiles#show",   as: :current_user_profile
  get '/profile/edit', to: "profiles#edit",   as: :edit_current_user_profile
  put '/profile',      to: "profiles#update", as: :update_current_user_profile

  resources :feeds do
    member do
      get :subscribe
    end
  end

  resources :home, only: [:index]

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  
  has_many :subscriptions
  has_many :users, through: :subscriptions

  has_many :bookmarks
  
  has_many :articles

  has_and_belongs_to_many :categories

  attr_accessible :description, :title, :url, :category_id

  validates_uniqueness_of :url

  def latest_articles
    articles.order('created_at DESC').limit(10)
  end
  
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    get_category_ids
    @feed = Feed.new(params[:feed])
    respond_to do |format|
      if @feed.save
        add_categories!
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    get_category_ids
    @feed = Feed.find(params[:id])
    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        add_categories!
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end

  def subscribe
    @feed = Feed.find(params[:id])
    @feed.subscriptions.create(user: current_user)
    redirect_to :back
  end
 
  private

  def get_category_ids
    @category_ids = params[:feed].delete(:category_ids)
  end

  def add_categories!
    categories = Category.find @category_ids
    @feed.categories = categories
  end


end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.haml
.yield-wrapper
  = form_for @feed do |f|
    .article-wrapper 
      - if @feed.errors.any?
        #error_explanation
          %h2= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
          %ul
            - @feed.errors.full_messages.each do |msg|
              %li= msg      
      .field
        %p="Enter the URL of the feed you want to add: " 
        = f.text_field :url
      .field
        %br
        %p="Select categories for your feed. Hold command to select several categories."
        .selectbox= select_tag("feed[category_ids][]", options_for_select(Category.all.collect { |category| [category.name.capitalize, category.id] }, @feed.categories.collect { |category| category.id }), {:multiple=>true, :size=>5})
        / = f.collection_select(:category_id, Category.all, :id, :name)
      .actions
        %br
        .bt= f.submit 'Save'

app/views/feeds/edit.html.haml
%h1 Editing feed

= render 'form'

= link_to 'Show', @feed
\|
= link_to 'Back', feeds_path

app/views/feeds/index.html.haml
%table
  %tr
    %th Name

  - @feeds.each do |feed|
    %tr
      %td= feed.title
      %td= link_to 'Show', feed
      / %td= link_to 'Subscribe' / 'Unsubscribe'
 

%br

= link_to 'New Feed', new_feed_path

app/views/feeds/new.html.haml
.headline new feed

= render 'form'

app/views/feeds/show.html.haml
%p#notice= notice
%p
  %h1= @feed.title   

  - @feed.latest_articles.each do |article|
    %h2= link_to article.title,  article, :target => "_blank"
    %br
    /   = raw article.content
    / %br

= link_to 'Back', feeds_path