config/routes.rb
RssFeedReader::Application.routes.draw do
  
  resources :subscriptions, only: [:index]


  devise_for :users#, controllers: {:registrations => "registrations", sessions: "sessions"}

  devise_scope :user do
    resources :users, only: [:index]
  end 

  root to: 'home#index'

  resources :articles

  resources :comments

  resources :bookmarks

  resources :categories

  resources :friendships

  get '/users/:user_id/profile', to: "profiles#show", as: :user_profile

  get :profile,        to: "profiles#show",   as: :current_user_profile
  get '/profile/edit', to: "profiles#edit",   as: :edit_current_user_profile
  put '/profile',      to: "profiles#update", as: :update_current_user_profile

  resources :feeds do
    member do
      get :subscribe
    end
  end

  resources :home, only: [:index]

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :friend, class_name: "User"

  attr_accessible :user_id, :friend_id
  
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friendships }
    end
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/new
  # GET /friendships/new.json
  def new
    @friendship = Friendship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/1/edit
  def edit
    @friendship = Friendship.find(params[:id])
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = Friendship.new(params[:friendship])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render json: @friendship, status: :created, location: @friendship }
      else
        format.html { render action: "new" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friendships/1
  # PUT /friendships/1.json
  def update
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      if @friendship.update_attributes(params[:friendship])
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy

    respond_to do |format|
      format.html { redirect_to friendships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.haml
= form_for @friendship do |f|
  - if @friendship.errors.any?
    #error_explanation
      %h2= "#{pluralize(@friendship.errors.count, "error")} prohibited this friendship from being saved:"
      %ul
        - @friendship.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :friend
    = f.text_field :friend
  .actions
    = f.submit 'Save'

app/views/friendships/edit.html.haml
%h1 Editing friendship

= render 'form'

= link_to 'Show', @friendship
\|
= link_to 'Back', friendships_path

app/views/friendships/index.html.haml
%h1 Listing friendships

%table
  %tr
    %th User
    %th Friend
    %th
    %th
    %th

  - @friendships.each do |friendship|
    %tr
      %td= friendship.user
      %td= friendship.friend
      %td= link_to 'Show', friendship
      %td= link_to 'Edit', edit_friendship_path(friendship)
      %td= link_to 'Destroy', friendship, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Friendship', new_friendship_path

app/views/friendships/new.html.haml
%h1 New friendship

= render 'form'

= link_to 'Back', friendships_path

app/views/friendships/show.html.haml
%table
  %tr
    %th Timeline

  - current_user.@feeds.each do |feed|
    %tr
      %td= feed.title
      %td= link_to 'Show', feed
      / %td= link_to 'Subscribe' / 'Unsubscribe'

%br