config/routes.rb
RssFeedReader::Application.routes.draw do
  
  resources :subscriptions, only: [:index]


  devise_for :users#, controllers: {:registrations => "registrations", sessions: "sessions"}

  devise_scope :user do
    resources :users, only: [:index]
  end 

  root to: 'home#index'

  resources :articles

  resources :comments

  resources :bookmarks

  resources :categories

  resources :friendships

  get '/users/:user_id/profile', to: "profiles#show", as: :user_profile

  get :profile,        to: "profiles#show",   as: :current_user_profile
  get '/profile/edit', to: "profiles#edit",   as: :edit_current_user_profile
  put '/profile',      to: "profiles#update", as: :update_current_user_profile

  resources :feeds do
    member do
      get :subscribe
    end
  end

  resources :home, only: [:index]

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_and_belongs_to_many :feeds

  attr_accessible :name
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
.headline categories
.yield-wrapper
  .article-wrapper
    - @categories.each do |category|
      .category= category.name.upcase
      / .article-title= category.feed.description
      .bt= link_to 'Show feeds', category
       

app/views/categories/new.html.haml
%h1 new category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice
.headline #{@category.name}
.yield-wrapper
  .article-wrapper
    - @category.feeds.each do |feed|
      .category= link_to feed.title, feed
      .bt= link_to 'Subscribe to feed', subscribe_feed_path
    %br
  .article-wrapper  
    .bt= link_to 'See all categories', categories_path